name: Count LOC 

on:
  push:
    branches: [ "main", "nightly" ]

jobs:
  count-loc:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.loc.outputs.loc }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install cloc

      - id: loc
        run: |
          LOC_VALUE=$(make line-count | tail -n 1)
          echo "loc=${LOC_VALUE}" >> "$GITHUB_OUTPUT"
        shell: bash
