name: Count LOC and Update Badge

on:
  push:
    branches: [ "main", "nightly" ]

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install cloc

      - name: Update README with LOC badge
        run: |
          LOC_VALUE=$(make line-count | tail -n 1)
          echo "::set-output name=loc::$LOC_VALUE"
        shell: bash
